// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _update_historyStatus2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_update_historyStatus2));
        
        string IMigrationMetadata.Id
        {
            get { return "202209081037052__update_historyStatus2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
